

services:
  mysql:
    image: mysql:8.0.42
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: email_sender
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  redis:
    image: redis:7.0.15-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


  email-sender-app:
    build: .
    image: email-sender-app
    environment:
      JWT_SECRET: ${JWT_SECRET_KEY}
      EMAIL_SECRET_APP_PASSWORD: ${EMAIL_SECRET_APP_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GMAIL_CLIENT_ID: ${GMAIL_CLIENT_ID}
      GMAIL_CLIENT_SECRET: ${GMAIL_CLIENT_SECRET}
      TOKEN_ENCRYPTION_KEY: ${TOKEN_ENCRYPTION_KEY}
      CONFIRMATION_EMAIL: ${CONFIRMATION_EMAIL}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: mysql
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"


volumes:
  mysql_data:
  redis_data:

